# Generated by Django 4.1 on 2022-10-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_listing_areaoccupied_listing_numberofbedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='Owner',
        ),
        migrations.AddField(
            model_name='listing',
            name='ListingGallery',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
