# Generated by Django 4.1 on 2022-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_listing_category_remove_listing_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ListingGallery',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
