# Generated by Django 4.1 on 2022-10-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_listing_listinggallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ListingGallery',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
