# Generated by Django 4.1 on 2022-10-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_listing_listinggallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ListingImage',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
