# Generated by Django 4.1 on 2022-10-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_listing_listingimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListingGallery', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='ListingImage',
        ),
        migrations.AlterField(
            model_name='listing',
            name='ListingGallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.listinggallery'),
        ),
    ]
