# Generated by Django 4.1 on 2022-10-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_listinggallery_remove_listing_listingimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ListingImage',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ListingGallery',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='ListingGallery',
        ),
    ]
