# Generated by Django 4.1 on 2022-10-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_rename_listinggallery_listing_listinggallerys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='ListingGallerys',
            new_name='ListingGallery',
        ),
    ]
