# Generated by Django 4.1 on 2022-10-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_rename_listinggallerys_listing_listinggallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingGallery2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery', models.FileField(default=None, upload_to='')),
                ('Name', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='Gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.listinggallery2'),
            preserve_default=False,
        ),
    ]
