# Generated by Django 4.1 on 2022-10-27 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_galleryimage_remove_listing_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='Listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.listing'),
        ),
    ]
